### ISSUE TITLE
Failed to activate the eval-selecshun package

### ISSUE THREAD

**Issue by Mackaber** [Jonahss/eval-selection#1]
It failed right away... 
(I'm also testing just testing Atom error reporting)

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [eval-selecshun](https://github.com/jonahss/eval-selection) package, v2.0.0
### Stack Trace

Failed to activate the eval-selecshun package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/mackaber/.atom/packages/eval-selecshun/lib/eval-selection.coffee:10:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:641:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:96:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-ruby, v0.1.0
eval-selecshun, v2.0.0

# Dev
No dev packages
```

**Comment by Jonahss** [comment]
@Mackaber 
Oh! Yeah they finally switched to the new api and I didn't update this package. Didn't know anyone else was using it and I've been kinda busy lately.

Would you like me to fix it?

**Comment by Mackaber** [comment]
Actually I just began using https://github.com/ardcore/atom-safe-eval, thanks for responding either way.
And no, I don't know anyone else who is using it...
